change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: true

#20 ticks = 1 second
nametag-refresh-interval-ticks: 20
tablist-refresh-interval-ticks: 20
header-footer-refresh-interval-ticks: 2
header:
- '%animation:ServerName%'
- ''
- '&6&lRank: %rank%'
- '&7&l>> %animation:Welcome%&3 &l%nick%&7&l! &7&l<<'
- '&7Online players: &f%online%'
- '&6Online staff: &e%staffonline%'
- '&2Balance: &f%vault_eco_balance% &6â™¦'
#- '%animation:ping-tps%'
- ''
- '%animation:MyAnimation1%'
footer:
- '%animation:MyAnimation1%'
- '%animation:time%'
- ''
- '&7Visit our discord' 
- '%animation:discord%'

#the yellow number in tablist
#options: PING, HEARTS, NONE (to disable it), CUSTOM (any placeholder defined below)
tablist-objective: NONE
tablist-objective-custom-value: '%some_placeholderapi_placeholder%'
#NOT case sensitive
group-sorting-priority-list:
- owner
- admin
- moderator
- helper
- builder
- donator
- premium
- rank
- mazerunner
- default
#properties: tabprefix, tabsuffix, tagprefix (in name tag), tagsuffix, customtabname (modifying the name itself), header, footer
#extra ones which need unlimited nametag mode enabled: abovename (line of text above name tag), belowname (below name tag), customtagname
Groups:
  Owner:
    tabprefix: '&6[&4&lO&6] &5'
    tagprefix: '&6[&k&4&lO&6] &5'
  Admin:
    tabprefix: '&6[&2&lA&6] &5'
    tagprefix: '&6[&2&lA&6] &5'
  Moderator:
    tabprefix: '&6[&b&lM&6] &5'
    tagprefix: '&6[&b&lM&6] &5'
  Helper: 
    tabprefix: '&6[&e&lH&6] &5'
    tagprefix: '&6[&e&lH&6] &5'
  Builder: 
    tabprefix: '&6[&4&lB&6&lu&e&li&2&ll&9&ld&1&le&5&lr&6] &5'
    tagprefix: '&6[&4&lB&6&lu&e&li&2&ll&9&ld&1&le&5&lr&6] &5'
  Donator:
    tabprefix: '&6[&6&lD&6] &f'
    tagprefix: '&6[&6&lD&6] &f'
  Premium:
    tabprefix: '&6[&5&lP&6] &f'
    tagprefix: '&6[&5&lP&6] &f'
  Rank:
    tabprefix: '&6[&1&lR&6] &f'
    tagprefix: '&6[&1&lR&6] &f'
  Mazerunner:
    tabprefix: '&6[&8&lM&6] &f'
    tagprefix: '&6[&8&lM&6] &f'
  Default:
    tabprefix: '&f'
    tagprefix: '&f'
  #any other group not defined above
  _OTHER_:
    tabprefix: '%vault-prefix% '
    tagprefix: '%vault-prefix% '
    tabsuffix: '%afk%'
    tagsuffix: '%afk%'
    customtabname: '%essentialsnick%'
    customtagname: '%essentialsnick%'

#personal settings, override group settings
Users:
  _NEZNAMY_:
    tabprefix: '&6&lTAB Author &a'
    tagprefix: '&6&lTAB &r&a'
    abovename: '&bOh look, 3 lines of text !'
    belowname: '&eThere''s only one plugin out there supporting it'

#servers and clients 1.9+
enable-collision: true

#preventing players in spectator gamemode from appearing at the bottom of tablist with transparent name FOR OTHER PLAYERS
do-not-move-spectators: true
#VERY EXPERIMENTAL !
#IF YOU EXPERIENCE ANY ISSUES CONTACT ME
unlimited-nametag-prefix-suffix-mode:
  enabled: false
  #modifying names of NPCs to avoid empty names on NPCs of online players
  #this blocks any other attemps to change the name visibility or anything, so you need to disable it if you are using some citizens addon that changes their name
  #needs relog to see the change
  modify-npc-names: false

#list of worlds with different settings than default, other worlds will use settings from above
per-world-settings:
  world1:
    header:
    - an example of world with custom
    footer:
    - header/footer and prefix/suffix
    Groups:
      Owner:
        tabprefix: '&0&l[&a&lOwner&0&l] &a'
        tagprefix: '&2&lOwner &a'
        header:
        - ur server man
        footer:
        - welcome
      Admin:
        tabprefix: '&2&lAdmin &1&l'
        tagprefix: '&2&lAdmin &1&l'
      Player:
        tabprefix: '&5&lPlayer &3&l'
        tagprefix: '&5&lPlayer &3&l'
    Users:
      Player1:
        tabprefix: 'Hi '
#setting output of some placeholders
placeholders:
  deluxetag-yes: < %value% >
  deluxetag-no: '&oNo Tag :('
  faction-yes: < %value% >
  faction-no: '&2Wilderness'
  afk-yes: ' &4*&4&lAFK&4*&r'
  afk-no: ''
  date-format: dd.MM.yyyy
  time-format: '[HH:mm]'
  #if time doesn't show correctly, you can change the time it shows
  #setting to -1 will make it show 1 hour less than it does currently, 1 makes it show one hour more than currently, 0 does nothing
  time-offset: 0
  #remove these strings from everywhere. Typically an empty output when using some clan/faction related plugin but player isn't in any
  #so players won't have empty brackets before their names
  remove-strings:
  - '[] '
  - '< > '

#better showing of %rank% placeholder
rank-aliases:
  Owner: '&4&lOWNER'
  Admin: '&2&lADMIN'
  Moderator: '&b&lMOD'
  Helper: '&e&lHELPER'
  Builder: '&4&lB&6&lU&e&lI&2&lL&9&lD&1&lE&5&lR'
  Donator: '&6&lDONATOR'
  Premium: '&5&lPREMIUM'
  Rank: '&1&lRANK'
  Mazerunner: '&8&lMAZERUNNER'
  #any other group not defined above
  _OTHER_: '&fNo Rank'

disable-features-in-worlds:
  header-footer:
  - disabledworld
  tablist-names:
  - disabledworld
  nametag:
  - disabledworld
  tablist-objective:
  - disabledworld
  bossbar:
  - disabledworld
  belowname:
  - disabledworld

#the vanilla belowname feature
#doesn't support player placeholders (faction, prefix), only server placeholders (time, date, animations) and static text
belowname:
  refresh-interval-ticks: 5
  number: '%health%'
  text: Health
  enabled: false
